### PR TITLE
Default logtostderr to true

### LINKED ISSUE #38: Make (also)logtostderr default to true
/kind feature

**Describe the solution you'd like**
I'd like to propose that `logtostderr` or `alsologtostderr` be defaulting to true. It's very common in the k8s community to have `init()` or `main()` functions to hardcode the flag to "true", flipping the default value of either flag should ease the use of this package and remove some initial friction for new users.

**Anything else you would like to add:**

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
This PR changes the default `logtostderr` to "true", more details and discussion can be found in #38.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #38

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
The `logtostderr` flag now defaults to true.
```

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Needs a release note.

**Comment by DirectXMan12** [comment]
seems reasonable to me though (as mentioned in the corresponding issue).

holding to make sure others get a chance to weigh in, but given that k8s.io/kubernetes does this already, I don't see much harm in changing this.

**Comment by dims** [comment]
/approve

leaving the lgtm for @DirectXMan12

**Comment by DirectXMan12** [comment]
well, that's two people.

I'll LGTM tomorrow or whenever we get a release note, whichever is later.

**Comment by vincepri** [comment]
@DirectXMan12 Added the release note :)

**Pull request merged**
