### PR TITLE
Using OS targeted go files to separate out the username logic.

### PR DESCRIPTION
**Pull request by phillipsj**
We have discovered that in some instances the runtime.GOOS="windows" check is failing on nanoserver when doing cross compilation. It appears to be inconsistent. Moving this into it's own OS targeted go file prevents it from being an issue.

Signed-off-by: Jamie Phillips <jamie.phillips@suse.com>

**What this PR does / why we need it**:

This PR removes the if runtime check in klog_file.go and moves the decision to compilation time. We have disovered that in some instances the if runtime check is failing on nanoserver and the code was dropping down into the else statement causing the net32api error that is in the comment for that code to be triggered.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by phillipsj** [comment]
I signed it

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by jayunit100** [comment]
this looks good - can we push it forward ? we need it for windows containers (nanoserveR) that use klog

**Pull request merged**
