### PR TITLE
glog wrapper that redirects to klog

### PR DESCRIPTION
**Pull request by dims**
implements the glog API, but redirects to klog implementation.

Makes it easy to use `dep` overrides to quickly switch/try the klog
implementation.

Change-Id: Ibdf4b25ed3b17e761c3fdea449f80add76a9070f

### CODE REVIEW

**Comment by dims** [comment]
cc @aledbf

**Comment by thockin** [comment]
What about the global flags?  Should we handle those more cleanly in klog, and make glog-shim globalize them?

**Comment by dims** [comment]
@thockin i wanted them to explicitly use the `klog. InitFlags(nil)` explicitly in their main even when they are using the glog-shim. Let's see if we see a pushback, we can always add it later. If we do add it right now, then it would be harder (especially when a repo will have some klog references and some glog-shim)

**Comment by neolit123** [comment]
LGTM
the compiler should inline the wrappers.

**Comment by dims** [comment]
self-approving based on @neolit123 's lgtm

**Pull request merged**
