### PR TITLE
Implemented IDE file navigation feature in buffer.go

### PR DESCRIPTION
**Pull request by inksnw**
**What this PR does / why we need it**:

To facilitate debugging and troubleshooting, it's often necessary to include detailed line number information in logs.
Ideally, these should be clickable, directing to the corresponding code location. 
To implement this feature, we just need to make the following configuration: add a space before and after "filename:line number" in the logs. GoLand/VSCode will then recognize it as a hyperlink.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Implemented IDE file navigation feature in buffer.go
```

### CODE REVIEW

**Comment by pohly** [comment]
This sounds very compelling. Unfortunately it is a breaking change that cannot be enabled by default because the current header is part of the klog API (log parsers might expect it). Would it be okay to make it configurable? Which binaries do you need this for?

**Comment by inksnw** [comment]
> This sounds very compelling. Unfortunately it is a breaking change that cannot be enabled by default because the current header is part of the klog API (log parsers might expect it). Would it be okay to make it configurable? Which binaries do you need this for?

There is no specific binary in mind; I intend for all developers using klog in their IDEs to benefit from this feature. To avoid a breaking change, I've added a flag 'hyperlink_headers'. 
Additionally, I noticed that klog/textlogger/textlogger.go also calls FormatHeader(), but I'm uncertain how to access the command-line flag within this file.The implementation might not be the most elegant, Any guidance or suggestions regarding this would be greatly appreciated. Thank you very much for your time and consideration.

**Comment by pohly** [comment]
To be honest, I am not sure whether this is worth it. It seems like a niche case that benefits only few developers from time to time, but a command line option will affect everyone because the CLI becomes even more cluttered than it is already.

We kind of put klog into pure maintenance mode with no new features, and this would be a new feature.

**Comment by inksnw** [comment]
> To be honest, I am not sure whether this is worth it. It seems like a niche case that benefits only few developers from time to time, but a command line option will affect everyone because the CLI becomes even more cluttered than it is already.
> 
> We kind of put klog into pure maintenance mode with no new features, and this would be a new feature.
> 
> 
> 
> 

I understand your concerns, maybe this is more suitable as a blog with development tips, rather than being merged into the code.

**Pull request closed without merging**
