### PR TITLE
chore: Bump go-logr from v0.2.0 to v0.3.0

### PR DESCRIPTION
**Pull request by greut**
**What this PR does / why we need it**:

Upgrades go-logr/logr to 0.3.0,  https://github.com/go-logr/logr/compare/v0.2.0...v0.3.0

Any libraries using go-logr directly and other k8s libraries with dependencies on klog will be able to use the new features from v0.3.0.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes n/a

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
> Any libraries using go-logr directly and other k8s libraries with dependencies on klog will be able to use the new features from v0.3.0.

Why does go-logr need to be bumped *in klog* for this? klog itself doesn't need those new features.

Downstream users are able to use a `require github.com/go-logr/logr v0.3.0` in their go.mod file and that is compatible with the existing klog.

**Comment by greut** [comment]
Agreed, the klog dependency on go-logr sees no improvement with that.

However, users of go-logr that picked klogr as a backend may appreciate the new features in 0.3.0

**Comment by pohly** [comment]
> However, users of go-logr that picked klogr as a backend may appreciate the new features in 0.3.0

Sorry, I still don't get it. The only new feature in 0.3.0 is context support. It makes no difference which version of go-logr is specified in klog. If a user wants those features, they need to `require` 0.3.0 and call the new API in their own projects.

**Comment by greut** [comment]
Okay, I'm still not full understanding _go modules_. It's not required.

**Pull request closed without merging**
