### PR TITLE
Fix  little nit for klog

### PR DESCRIPTION
**Pull request by yuzhiquan**
**What this PR does / why we need it**:
Fix some little nit for klog which is in study some source code .
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@yuzhiquan please squash the commits.

**Comment by yuzhiquan** [comment]
> @yuzhiquan please squash the commits.

@dims  Done

**Pull request merged**
