### PR TITLE
remove depend github.com/go-logr/logr， fix issue Logger changed from interface to struct

### PR DESCRIPTION
**Pull request by RyouZhang**
Signed-off-by: ryouzhang ryouzhang@gmail.com

**What this PR does / why we need it**: 
remove depend on github.com/go-logr/logr fix issue Logger changed from interface to struct 
Copy github.com/go-logr/log Logger interface to klog

### CODE REVIEW

**Comment by serathius** [comment]
Hey @RyouZhang, can you provide what are the goals of this change? 

logr change to struct is motivated by performance improvement, but still leaves same level of customization by allowing users to provide LogSink interface. I understand that logr switching to struct will require some changes, however klog is not interested in creating it's own interface.  

We are already working on adjusting klog to work with 1.0 release.  Maybe you are interested in helping with it https://github.com/kubernetes/klog/pull/242

**Comment by RyouZhang** [comment]
I don‘t think change logr.Logger to *logr.Logger is a good idea, it's a break changed.

**Comment by RyouZhang** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

/check-cla

**Comment by serathius** [comment]
> I don‘t think change logr.Logger to *logr.Logger is a good idea, it's a break changed.
> in v0.4.0 logr define Logger interface, you can use any logger libs(like zap)
> but v1.0.0 the klog deep depend logr.Logger

Fact that logr.Logger is now a struct doesn't change the fact that you can define your our interface (like zap) to be used to format logs. It's just that `logr` split interface into client (logr.Logger) from logging library interface (logr.LogSink). If you still want to use zap you can provide your own LogSink.

**Comment by RyouZhang** [comment]
> > I don‘t think change logr.Logger to *logr.Logger is a good idea, it's a break changed.
> > in v0.4.0 logr define Logger interface, you can use any logger libs(like zap)
> > but v1.0.0 the klog deep depend logr.Logger
> 
> Fact that logr.Logger is now a struct doesn't change the fact that you can define your our interface (like zap) to be used to format logs. It's just that `logr` split interface into client (logr.Logger) from logging library interface (logr.LogSink). If you still want to use zap you can provide your own LogSink.

So why  change logr.Logger to *logr.Logger, logr.LogSink is better.
I think logger is a interface like a protocol

**Comment by thockin** [comment]
logr.Logger is *effectively* an interface, but using a literal Go interface has performance costs that can not be optimized.  Changing it to a struct means that the Go optimizer can (eventually) elide a lot of copying and unpacking and repacking operations.

It's still an abstract API, it's just that the implementations plug in one layer further down, now.

**Comment by thockin** [comment]
I suggest we close this :)

**Pull request closed without merging**
