### PR TITLE
de-duplication of key/value pairs

### PR DESCRIPTION
**Pull request by pohly**
**What this PR does / why we need it**:

Previously, de-duplication was limited such that keys passed to a log call as
parameters overwrote keys passed earlier to WithValues. Using the same key in
different WithValues calls or multiple times in a WithValues call or the
parameters led to duplicates in the output.
    
Now all key/value pairs get checked for duplicates. The last one wins and is
printed at the place where it was added. If a second occurrence is the same as
a prior one, the first one is kept and the second is discarded.

This is partly motivated by the concern that adding OpenTelemetry will lead to
duplicate IDs (cc @dashpole), partly by prior discussions around instrumentation
not being able to avoid duplicates when using WithValue when the instrumentation
is happening in unrelated packages (cc @sbueringer, if I remember correctly).

**Special notes for your reviewer**:

Because the new implementation avoids memory allocations does very little extra work
when there is nothing which needs to be de-duplicated, the performance
impact is minimal. Some cases even become faster. See commit messages for
benchmark results.

**Release note**:

```release-note
The klog text output now consistently de-duplicates key/value pairs such that any given key is  only printed once with its most recent value.
```

### CODE REVIEW

**Comment by pohly** [comment]
This should be ready for a review.

@mengjiao-liu, @harshanarayana, who has time?

**Comment by harshanarayana** [comment]
Checking @pohly

**Review by mengjiao-liu — COMMENTED** [review]
I debugged the log outputs,  and these tests were passed.
Just a non-blocking comment, LGTM otherwise!

**Comment by mengjiao-liu** [comment]
/lgtm
/hold
Waiting for your reconfirmation.@harshanarayana

**Review by harshanarayana — COMMENTED** [review]
/lgtm 

/cc @dims

**Comment by pohly** [comment]
/assign @dims 

For approval - I don't want to self-approve this. Please lift the hold if you agree to merge this.

**Comment by dims** [comment]
/hold cancel

thanks @pohly @harshanarayana

**Comment by sbueringer** [comment]
Thx!

**Pull request merged**
