### PR TITLE
Bootstrapping a team to take care of klog

### LINKED ISSUE #44: Bootstrapping a team to take care of klog
The following folks have expressed interested on email/slack:
https://groups.google.com/forum/#!msg/kubernetes-dev/DKWQn2a3Ybw/Z-07nwabDwAJ

@yagonobre 
@vincepri 
@detiber 
@jaredallard

Anyone else?

### PR DESCRIPTION
**Pull request by dims**
Change-Id: Ie566088f45712e6a38fcfbc0ddaf98a07387c5b5

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #44

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by DirectXMan12** [comment]
I don't actually recall if the bot is case-sensitive -- we had a problem a while ago where you had to use the proper capitalization for people's names (had to do with interaction with the GitHub API).  Might want to leave my name alone just in case.

**Comment by dims** [comment]
@jayunit100 @hoegaarden  @andyxning @neolit123 @pohly @yagonobre @vincepri @detiber it's up to you all now to take care of this! :)

**Comment by neolit123** [comment]
yikes
/lgtm
/hold

**Comment by neolit123** [comment]
/hold cancel
the list of folks already agreed. if someone wants out, please send a PR. :)

**Pull request merged**
