### PR TITLE
Add go modules files

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
This PR adds `go.mod` and `go.sum` files that get added if you have modules enabled locally.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by pohly** [comment]
Do we need these extra files, i.e. what is the drawback if we don't add them?

**Comment by vincepri** [comment]
If you have go modules enabled, it'll auto-generate these when running go get or any other command, given that k/k has moved to modules in 1.15 I assumed we'd want to do the same here

**Comment by pohly** [comment]
We could also add these files to `.gitignore`. What advantage does it have for users of this package if we add them to the repo? What kind of maintenance do we need to do on these files to ensure that users really benefit from them?

**Comment by vincepri** [comment]
I don't think we should ignore these files, Go modules will be on by default in Go 1.13, users updating this repository and adding dependencies will need to add them in here, which seems rare.

**Comment by pohly** [comment]
> users updating this repository and adding dependencies will need to add them in here

Not if we have the files in `.gitignore`...

Sorry, I'm really just trying to understand what difference it makes for users of this package or developers whether we have `go.mod` and `go.sum` in the repo. Consider it a chance to educate me :smile: 

As an experiment, I just created a dumb test project which uses Go modules and I could add this package with `go get k8s.io/klog` just fine. So for users I don't think this PR makes any difference.

It might be relevant at some point if we start to add dependencies for which we want to record the minimal version, but the files can also be added then.

@neolit123: any opinion?

**Comment by neolit123** [comment]
nowadays, it's a standard practice to enable go modules across k8s repositories.
given klog only depends on logr it allows us to pin a specific version of logr which is still viable.

i'm +1 for adding the go files.

**Comment by pohly** [comment]
Okay, so let's get onto the bandwagon even if it is just for the sake of it :smile:

/lgtm
/approve

**Comment by Katharine** [comment]
/hold

github search is busted and tide is stuck trying to merge this already-merged PR forever.

**Pull request merged**
