### PR TITLE
Add apidiff script to check go signature changes

### PR DESCRIPTION
**Pull request by dims**
Signed-off-by: Davanum Srinivas <davanum@gmail.com>

**What this PR does / why we need it**:
Similar to what we did in k8s.io/utils repo ( https://github.com/kubernetes/utils/pull/158 )

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
looks the same as https://github.com/kubernetes/utils/pull/158

/lgtm
/hold

feel free to unhold.

**Comment by liggitt** [comment]
mind adding a tmp commit that breaks the go api to verify this works?

**Comment by dims** [comment]
The following change
```
diff --git a/klog.go b/klog.go
index 63426f58..43b217a7 100644
--- a/klog.go
+++ b/klog.go
@@ -828,7 +828,7 @@ func SetLogger(logr logr.Logger) {
 }
 
 // SetOutput sets the output destination for all severities
-func SetOutput(w io.Writer) {
+func SetOutput(w io.Writer) error {
 	logging.mu.Lock()
 	defer logging.mu.Unlock()
 	for s := fatalLog; s >= infoLog; s-- {
@@ -837,6 +837,7 @@ func SetOutput(w io.Writer) {
 		}
 		logging.file[s] = rb
 	}
+	return nil
 }
 
 // SetOutputBySeverity sets the output destination for specific severity
```

Produced the following error:
```
Run ./hack/verify-apidiff.sh -d ../old
Inspecting API of ../old...
go: downloading github.com/go-logr/logr v0.1.0
go: extracting github.com/go-logr/logr v0.1.0
go: finding github.com/go-logr/logr v0.1.0
Comparing with ../old...
FAIL: k8s.io/klog/v2 contains incompatible changes:
- SetOutput: changed from func(io.Writer) to func(io.Writer) error

##[error]Process completed with exit code 1.
```

**Pull request merged**
