### PR TITLE
Prevents calling `logr.(Info|Error)` with a wrapped slice in slice.

### PR DESCRIPTION
**Pull request by blaubaer**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes *none*

**Release note**:

```release-note
Fixes: Prevents calling `logr.(Info|Error)` with a wrapped slice in slice.
```

### CODE REVIEW

**Comment by dims** [comment]
@blaubaer can you please add a quick test as well?

**Comment by blaubaer** [comment]
@dims Sure, makes totally sense. :-)

**Comment by dims** [comment]
@blaubaer can you please rebase?

**Pull request merged**
