### PR TITLE
Check new klog flag's prefix

### LINKED ISSUE #191: Ensure flags added in klog have a prefix to identify where the flag came from
feedback from @liggitt in: https://github.com/kubernetes/kubernetes/pull/96154#issuecomment-721764666

### PR DESCRIPTION
**Pull request by yuzhiquan**
**What this PR does / why we need it**:
check new klog flag's prefix
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #191 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```
/assign @dims

### CODE REVIEW

**Comment by brancz** [comment]
cc @serathius

**Comment by dims** [comment]
cc @liggitt

**Comment by yuzhiquan** [comment]
Gently ping @liggitt

**Comment by dims** [comment]
/approve
/lgtm

thanks @yuzhiquan

**Pull request merged**
