### PR TITLE
WIP: test(*): TestRollover failed randomly on Windows

### PR DESCRIPTION
**Pull request by lsytj0413**
**What this PR does / why we need it**:

I found this was cased by TestSetOutputDataRace function，it called SetOutputBySeverity/SetOutput in another goroutine which maybe change INFO level logfile to redirectBuffer after TestSetOutputDataRace done。This behavior broken TestRollover randomly。

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by lsytj0413** [comment]
https://github.com/kubernetes/klog/pull/136
https://github.com/kubernetes/klog/issues/133

**Comment by dims** [comment]
@lsytj0413 please remove WIP if this is ready to merge. Also i don't mind bringing in the commit from https://github.com/kubernetes/klog/pull/136 to this PR so we can be sure that the windows stuff is really ready.

**Comment by sebsoto** [comment]
Should `wg.Add(1)` be added to the goroutines calling `logging.flushDaemon`, to prevent possible issues in the future?

**Comment by neolit123** [comment]
added in https://github.com/kubernetes/klog/pull/136
thanks
/close

**Comment by lsytj0413** [comment]
> Should `wg.Add(1)` be added to the goroutines calling `logging.flushDaemon`, to prevent possible issues in the future?

can't do this because logging.flushDaemon never return.

**Pull request closed without merging**
