### PR TITLE
feat(klogr): print error verbose like what zap does

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

**What this PR does / why we need it**:

Printing `errorVerbose` with `logr.Error()`, just like what zap dose.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
print errorVerbose for logr.Error()
```

### CODE REVIEW

**Comment by STRRL** [comment]
/check-cla
--

**Comment by pohly** [comment]
Why is this useful?

Always logging `errVerboseStr=" "` doesn't add any information, so why not leave it out?

**Comment by STRRL** [comment]
> Why is this useful?
> 
> Always logging `errVerboseStr=" "` doesn't add any information, so why not leave it out?

The content of `errVerboseStr` is `fmt.Sprintf("%+v", err)`, that one whitespace is just a separator.

It will be very useful with the error which contains stack frames like `errors.New("message")` with https://github.com/pkg/errors.

**Comment by STRRL** [comment]
> I'm still unsure about how useful this is. I assume it's configurable in zap?
> 
> It would be better to have an option in klogr for enabling it, with "off" the default.

It would not be soo much useful after widely using `github.com/pkg/errors`. 

I am going to close this PR.

**Pull request closed without merging**
